### ISSUE TITLE
[Suggestion] Switch to a free physics engine

### ISSUE THREAD

**Issue by flarn2006** [openai/multi-agent-emergence-environments#40]
This depends on the proprietary MuJoCo physics engine, which apparently requires a subscription-based license for extended use. So would it be feasible to eliminate this dependency and replace it with something else? A free, open-source physics engine would be ideal, but even one that's just free as in beer (without any trial period or student requirement) would be a great improvement.

I know the readme says this repository is no longer being updated, but hopefully there's someone (from OpenAI or otherwise) who would be interested in taking this on as a project.

**Comment by NathanGavenski** [comment]
The repository is archived. They will not update any further. Perhaps we could fork this repository and start supporting it. I see there are plenty of issues with status open.

**Comment by HACLANG** [comment]
MuJoCo is now free and open source

**Comment by flarn2006** [comment]
@HACLANG Oh wow, that's awesome! Guess I'll close this issue now. :) Thanks for letting me know.
